apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskdemo
  template:
    metadata:
      labels:
        app: flaskdemo
    spec:
      containers:
      - image: himateja0206/flaskdemo:latest
        name: flaskdemo
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Config
clusters:
  ...
contexts:
  ...
current-context: ...
preferences: {}
users:
  - name: minikube
    user:
      client-certificate-data: <base64 -w 0 /home/himateja/.minikube/profiles/minikube/client.crt>
      client-key-data: <base64 -w 0 /home/himateja/.minikube/profiles/minikube/client.key>
      

---
apiVersion: v1
kind: Service
metadata:
  name: flaskdemo-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: flaskdemo
